# Generated by Django 5.0.6 on 2024-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena')),
                ('quantity', models.PositiveIntegerField(verbose_name='ilosc dostepnych sztuk')),
                ('category', models.CharField(max_length=255, verbose_name='kategoria')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
            ],
        ),
    ]
